services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogs
      PGDATABASE: blogs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read

    environment:
      - DATABASE_URL=postgres://user:password@db:5432/blogs
      - SECRET=sdjjds@sd£$(Dg)
    container_name: blog-backend # This will name the container todo-frontend-dev
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  app:
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    container_name: blog-frontend
    depends_on:
      - server

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server # wait for the frontend container to be started
